
FACE_NUM_VERTS   = (2340 // 5)
FACE_NUM_FLOATS  = FACE_NUM_VERTS * 8
FACE_NUM_INDICES = 2640

USE_PYTHON = False
USE_CPP = False

IMG_W = None
IMG_H = None

FOCAL_LENGTH = None

# USER_INTERPUPILLARY_DISTANCE = None
# USER_BROW_PHILTRUM_DISTANCE  = None
